### PR TITLE
edit main readme and add accessible links

### PR DESCRIPTION
**Pull request by soulbliss**
Here are the edits in this PR

-  change ```Fields``` folder to ```Topics``` for clarity
-  make latest links like Placement details/schedules available on top Readme file
   - add image in main readme as many peeps wont open an excel file.
-  Shift details of folder details from main readme to contributing guidelines file
   -  For example a line like this ```Resources related to the placements are in the Placement folder.```
      has been shifted to contributing guidelines file
- added a tree structure in contributing guidelines file to understand repo structure

### CODE REVIEW

**Comment by soulbliss** [comment]
@Sambhav300899 @TheProjectsGuy let know if it's good to be merged

**Comment by TheProjectsGuy** [comment]
I was navigating the README. Appreciate the modifications. 
I think the README in Placements directory is never seen. There are some resources for placements there (like sites to see and stuff). 
Any suggestions on making those visible through a link in the main README?

**Comment by TheProjectsGuy** [comment]
I have an idea. Maybe add the links to the folders in the headers on the main README.

**Comment by soulbliss** [comment]
That skipped my mind. Glad you pointed out.

And one more thing, the resources in placements should have header 2, as opposed to within  batch summary.

Then these resources can be pointed in the main Readme under the placement header with aptitude and coding sections. What say?

**Pull request merged**
