### PR TITLE
Compartmentalised everything into folders

### PR DESCRIPTION
**Pull request by TheProjectsGuy**
I've compartmentalized everything into designated folders. Please review the files added.
I've also restructured the README and have added contribution guidelines to the project (and some resources for the new contributors).

Feel free to comment

### CODE REVIEW

**Comment by soulbliss** [comment]
@Sambhav300899 take a look at this PR.
It's a properly organised PR of our existing README file.

@TheProjectsGuy There are certain points that I have.
- Valuable information seems to be burried deep down within the project structure,
  although valuable in the longer run, however in the initial stages, may cause people to search a lot 
  for the content. 
- Will propose some minor changes in your commit, specifically to the headers, so that it addresses 
  the first point.

Once again, nicely organised :)

**Comment by TheProjectsGuy** [comment]
> @Sambhav300899 take a look at this PR.
> It's a properly organised PR of our existing README file.
> 
> @TheProjectsGuy There are certain points that I have.
> 
>     * Valuable information seems to be burried deep down within the project structure,
>       although valuable in the longer run, however in the initial stages, may cause people to search a lot
>       for the content.
> 
>     * Will propose some minor changes in your commit, specifically to the headers, so that it addresses
>       the first point.
> 
> 
> Once again, nicely organised :)

Will you be working on my branch?

**Comment by soulbliss** [comment]
yes

**Comment by TheProjectsGuy** [comment]
How about we add a few links to the most important files in the category (sort of the _latest_ stuff) to the main README of the repository?

**Comment by soulbliss** [comment]
yeah for example the [Fields](https://github.com/Sambhav300899/MIT-Mechatronics-Resources/blob/avneesh_2016/Course/Fields/README.md) seems to be deep down, 
if we could for initial stages link the important TOC (table of contents on the main README, that would do to)

For example in your branch avneesh_2016
the line
```
Resources related to the placements are in the Placement folder
```

could be replaced by 


  - [Batch wise summary](https://github.com/Sambhav300899/MIT-Mechatronics-Resources/tree/avneesh_2016/Placements#batch-wise-summary)
    - [2020](https://github.com/Sambhav300899/MIT-Mechatronics-Resources/tree/avneesh_2016/Placements#2020)
      - [Placement Schedule](https://github.com/Sambhav300899/MIT-Mechatronics-Resources/tree/avneesh_2016/Placements#placement-schedule)
      - [Resources](https://github.com/Sambhav300899/MIT-Mechatronics-Resources/tree/avneesh_2016/Placements#resources)

**Comment by TheProjectsGuy** [comment]
Work is needed on Placements... Maybe add those changes in another commit?
We don't seem to have enough data

**Comment by soulbliss** [comment]
> Work is needed on Placements... Maybe add those changes in another commit?
> We don't seem to have enough data

Yeah I agree. That we can resolve in other commit.

For now I want to introduce some changes in the Main Readme of your branch, so things are accessible on top. Hope it's fine.

**Comment by TheProjectsGuy** [comment]
I’ll just upload the excel file and add a link to that for now. 
Is anybody on the campus? (Faculty will also work). They can get the data. Or, we can request the placement department.

**Comment by soulbliss** [comment]
Yeah Shasank sir is there near campus, not sure if they go to college.

I think we should create a new issue specifically for placements, things can be categorised there

**Comment by TheProjectsGuy** [comment]
Okay, I'll resolve the README conflict then.

**Pull request merged**
